name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: yarn --frozen-lockfile
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - run: yarn --frozen-lockfile
      - run: yarn test
